version: "3.8"
services:
  app:
    restart: unless-stopped
    build: .
    environment:
      - C_USER=app
      - C_UID=1000
      - C_GROUP=app
      - C_GID=1000
      - C_HOME=/app
      - C_CUSTOMSCRIPTS_PATH=/etc/custom-scripts
      - C_TIMEZONE=Europe/Copenhagen
    volumes:
      - ./custom-scripts:/etc/custom-scripts
